services:
  web:
    container_name: db_service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - rec-sys-network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_DB=rec_sys_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./src/dataset:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rec-sys-network

networks:
  rec-sys-network:
    external: true
    name: rec-sys-network
    driver: bridge

volumes:
  postgres-data:
