services:
  web:
    container_name: ml_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: always
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge