services:
  web:
    container_name: ml_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: always
    networks:
      - rec-sys-network
networks:
  rec-sys-network:
    name: rec-sys-network
    driver: bridge