services:
  krakend:
    container_name: krakend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - rec-sys-network
networks:
  rec-sys-network:
    name: rec-sys-network
    driver: bridge
      